apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - patches/namespace.yaml
  - patches/ip-pool.yaml
  - patches/l2-advertisement.yaml
helmCharts:
- name: metallb
  releaseName: metallb
  namespace: metallb-system
  version: 0.14.3
  repo: https://metallb.github.io/metallb
  valuesFile: values.yaml
  includeCRDs: true